import json
import tempfile
import unittest
from pathlib import Path

from tools.blender.pbr_bake_export.addon.manifest import ExportManifest, write_manifest
from tools.blender.pbr_bake_export.addon.types import AssetMode, MaterialSource, TextureResolution


class ManifestTests(unittest.TestCase):
    def test_write_manifest_outputs_stable_relative_paths(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            manifest = ExportManifest(
                asset_name="wall_panel",
                source_object="Wall Panel",
                exported_at="2026-06-22T12:00:00-04:00",
                mode=AssetMode.LOW_POLY,
                autogenerated_low_poly=True,
                resolution=TextureResolution.FOUR_K,
                material_source=MaterialSource.POLY_HAVEN,
                polyhaven_asset_id="red_brick_floor",
                glb="wall_panel.glb",
                textures={
                    "basecolor": "textures/wall_panel_basecolor.png",
                    "normal": "textures/wall_panel_normal.png",
                    "roughness": "textures/wall_panel_roughness.png",
                    "metallic": "textures/wall_panel_metallic.png",
                    "ao": "textures/wall_panel_ao.png",
                },
                warnings=["roughness used constant 0.5"],
            )

            write_manifest(root / "manifest.json", manifest)

            text = (root / "manifest.json").read_text(encoding="utf-8")
            data = json.loads(text)
            self.assertEqual(data["asset_name"], "wall_panel")
            self.assertEqual(data["mode"], "Low Poly")
            self.assertEqual(data["resolution"], 4096)
            self.assertEqual(data["material_source"], "Poly Haven")
            self.assertEqual(data["textures"]["normal"], "textures/wall_panel_normal.png")
            self.assertEqual(data["warnings"], ["roughness used constant 0.5"])
            self.assertTrue(text.endswith("\n"))
            self.assertEqual(list(data.keys()), sorted(data.keys()))


if __name__ == "__main__":
    unittest.main()
