"""Manifest serialization for Blender PBR exports."""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Mapping

from .types import AssetMode, MaterialSource, TextureResolution


@dataclass(frozen=True)
class ExportManifest:
    asset_name: str
    source_object: str
    exported_at: str
    mode: AssetMode
    autogenerated_low_poly: bool
    resolution: TextureResolution
    material_source: MaterialSource
    polyhaven_asset_id: str | None
    glb: str | Path
    textures: Mapping[str, str | Path]
    warnings: list[str] = field(default_factory=list)


def _manifest_path(value: str | Path) -> str:
    return Path(value).as_posix()


def write_manifest(path: Path, manifest: ExportManifest) -> None:
    output = {
        "asset_name": manifest.asset_name,
        "source_object": manifest.source_object,
        "exported_at": manifest.exported_at,
        "mode": manifest.mode.value,
        "autogenerated_low_poly": manifest.autogenerated_low_poly,
        "resolution": manifest.resolution.pixel_size,
        "material_source": manifest.material_source.value,
        "polyhaven_asset_id": manifest.polyhaven_asset_id,
        "glb": _manifest_path(manifest.glb),
        "textures": {
            role: _manifest_path(texture_path)
            for role, texture_path in manifest.textures.items()
        },
        "warnings": list(manifest.warnings),
    }

    path = Path(path)
    if path.parent:
        path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(output, indent=2, sort_keys=True) + "\n", encoding="utf-8")
